---
title: "devon"
format: html
editor: visual
---

# Add necessary libraries and helper functions 
```{r}
library(readr)
library(tidyverse)
source("karen-helper-fns.R")
```

# Read in data

```{r}
karen <- read.csv("full-names-data-nice.csv")
```

# Find Correlation for Devon

```{r}
# Filter down to male Devons in USA
devon_us <- karen %>%
  filter(name == "Devon", sex == "Boy", country == "United States")

# Filter down to male Devons in England/Wales
devon_eng <- karen %>%
  filter(name == "Devon", sex == "Boy", country == "England/Wales")

# Find the years which both dfs have in common
common_yrs_devon <- inner_join(x = devon_us, y = devon_eng, by = c("year"))

# Filter to Devons USA Proportions
devon_us_props <- common_yrs_devon %>%
  select(prop.x)

# Filter to Devons England/Wales Proportions
devon_eng_props <- common_yrs_devon %>%
  select(prop.y)

# Find correlation
helperCor(devon_us_props, devon_eng_props)
```

# Find Correlation for Jordan

```{r}
# Filter down to male Jordans in USA
jordan_us <- karen %>%
  filter(name == "Jordan", sex == "Girl", country == "United States")

# Filter down to male Jordans in England/Wales  
jordan_eng <- karen %>%
  filter(name == "Jordan", sex == "Girl", country == "England/Wales")

# Find the years which both dfs have in common
common_yrs_jordan <- inner_join(x = jordan_us, y = jordan_eng, by = c("year"))

# Filter to Jordans USA Proportions
jordan_us_props <- common_yrs_jordan %>%
  select(prop.x)

# Filter to Jordans England/Wales Proportions
jordan_eng_props <- common_yrs_jordan %>%
  select(prop.y)

# Find correlation
helperCor(jordan_us_props, jordan_eng_props)
```

