---
title: "jordan"
format: html
---

# Issue 5 : Find the correlation with US Karen data and the other three countries in the future 60 years. (assume only female Karens)

# Package
```{r}
library(tidyverse)
library(here)
```


# Read in Data 
```{r}
data <- read.csv(here("full-names-data-nice.csv"))
```


#Find Corr 
```{r}
data <- data %>% 
  rename_with(tolower)

# US DF 
us_df <- data %>% 
  filter(country == "US" &
           name == "Karen" &
           sex == "Girl") %>% 
  arrange(year)

#US to england/wales 
karen_ew_df <- data %>% 
  filter(country == "England/Wales" &
           name == "Karen" &
           sex == "Girl") %>% 
  arrange(year)

us_ew_line_up <- help_line_up(karen_ew_df, us_df)

us_ew_line_up <- us_ew_line_up %>% arrange(year)

us_df_2 <- us_ew_line_up%>% filter(country == "US") %>% arrange(year)
ew_df_2 <- us_ew_line_up%>% filter(country == "England/Wales") %>% arrange(year)

helperCorLagKaren(ew_df_2, 60, us_df_2)



#US with NI 
ni_df <- data %>% filter(country == "Northern Ireland" &
                    name == "Karen" &
                    sex == "Girl")  %>% arrange(year)
line_up2 <- help_line_up(ni_df, us_df)
us_df_3 <- line_up2 %>% filter(country == "US") %>% arrange(year)
ni_df2 <- line_up2 %>% filter(country == "Northern Ireland") %>% arrange(year)

helperCorLagKaren( ni_df2, 60,us_df_3) 
# US with Scotland 
scot_df <- data %>% filter(country == "Scotland" &
                    name == "Karen" &
                    sex == "Girl") %>% arrange(year)
line_up3 <- help_line_up(scot_df, us_df)
us_df_4 <- line_up3 %>% filter(country == "US") %>% arrange(year)
scot_df2 <- line_up3 %>% filter(country == "Scotland") %>% arrange(year)

helperCorLagKaren(scot_df2,60,us_df_4) 
```


